CREATE TABLE reddit_olap_dwh.`dim_comment` (
  `comment_key` int(8) NOT NULL AUTO_INCREMENT,
  `comment_last_update` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `comment_author` varchar(20) DEFAULT NULL,
  `comment_author_cakeday`  varchar(20) DEFAULT NULL,
  `comment_author_flair_type` varchar(20) DEFAULT NULL,
  `comment_author_patreon_flair` varchar(20) DEFAULT NULL,
  `comment_body` varchar(1000) DEFAULT NULL,
  `comment_can_gild` boolean DEFAULT NULL,
  `comment_controversiality` int(8) DEFAULT NULL,
  `comment_created_utc` datetime DEFAULT NULL,
  `comment_distinguished` int(8) DEFAULT NULL,
  `comment_gilded` int(8) DEFAULT NULL,
  `comment_is_submitter` boolean DEFAULT NULL,
  `comment_locked` boolean DEFAULT NULL,
  `comment_mod_remove` boolean DEFAULT NULL,
  `comment_no_follow` boolean DEFAULT NULL,
  `comment_reply_delay` int(8) DEFAULT NULL,
  `comment_score` int(8) DEFAULT NULL,
  `comment_send_replies` boolean DEFAULT NULL,
  `comment_stickied` boolean DEFAULT NULL,
  `comment_subreddit` varchar(20) DEFAULT NULL,
  `comment_subreddit_type` varchar(20) DEFAULT NULL,
  `comment_total_awards_received` int(8) DEFAULT NULL,
  `comment_user_removed` boolean DEFAULT NULL,
  PRIMARY KEY (`comment_key`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1