CREATE TABLE reddit_olap_dwh.`dim_subreddit` (
  `subreddit_key` int(8) NOT NULL AUTO_INCREMENT,
  `subreddit_last_update` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `subreddit_restrict_posting` boolean DEFAULT NULL,
  `subreddit_free_form_reports` boolean DEFAULT NULL,
  `subreddit_wiki_enabled` boolean DEFAULT NULL,
  `subreddit_display_name` varchar(64) DEFAULT NULL,
  `subreddit_header_img` varchar(64) DEFAULT NULL,
  `subreddit_title`  varchar(64) DEFAULT NULL,
  `subreddit_active_user_count` int(8) DEFAULT NULL,
  `subreddit_accounts_active` int(8) DEFAULT NULL,
  `subreddit_public_traffic` boolean DEFAULT NULL,
  `subreddit_subscribers` int(8) DEFAULT NULL,
  `subreddit_emojis_enabled` boolean DEFAULT NULL,
  `subreddit_public_description` varchar(200) DEFAULT NULL,
  `subreddit_comment_score_hide_mins` int(8) DEFAULT NULL,
  `subreddit_original_content_tag_enabled` boolean DEFAULT NULL,
  `subreddit_submit_text` varchar(200) DEFAULT NULL,
  `subreddit_spoilers_enabled` boolean DEFAULT NULL,
  `subreddit_all_original_content` boolean DEFAULT NULL,
  `subreddit_has_menu_widget` boolean DEFAULT NULL,
  `subreddit_created_utc` date DEFAULT NULL,
  `subreddit_submission_type` varchar(20) DEFAULT NULL,
  `subreddit_allow_videogifs` boolean DEFAULT NULL,
  `subreddit_collapse_deleted_comments` boolean DEFAULT NULL,
  `subreddit_allow_videos` boolean DEFAULT NULL,
  `subreddit_type` varchar(20) DEFAULT NULL,
  `subreddit_show_media`  boolean DEFAULT NULL,
  `subreddit_over18` boolean DEFAULT NULL,
  `subreddit_description` varchar(200) DEFAULT NULL,
  `subreddit_allow_images` boolean DEFAULT NULL,
  `subreddit_lang` boolean DEFAULT NULL,
  PRIMARY KEY (`subreddit_key`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1